kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: ltalreja@gmail.com
        send_resolved: false
        from: the.resume.builder.app@gmail.com
        smarthost: smtp.eample.com:587
        auth_username: the.resume.builder.app@gmail.com
        auth_password: Abc@1234
        auth_secret: the.resume.builder.app@gmail.com
        auth_identity: the.resume.builder.app@gmail.com
        require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#alerts-group4'